/*Generated by WaveMaker Studio*/

package com.testmobile.database29thsep.dao;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Repository;
import org.springframework.orm.hibernate4.HibernateTemplate;

import com.wavemaker.runtime.data.dao.WMGenericDaoImpl;

import com.testmobile.database29thsep.*;
/**
 * Specifies methods used to obtain and modify Sample related information
 * which is stored in the database.
 */
@Repository("Database29thSep.SampleDao")
public class SampleDao extends WMGenericDaoImpl <Sample, Integer> {

   @Autowired
   @Qualifier("Database29thSepTemplate")
   private HibernateTemplate template;

   public HibernateTemplate getTemplate() {
        return this.template;
   }
}

